swagger: '2.0'
info:
  version: 1.0.0
  title: Email Utility
  description: Email Utility for use by University developers
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: OIT Service Desk Support
    url: 'https://it.byu.edu'
    email: it@byu.edu
paths:
  '/{user_id}/messages':
    get:
      summary: Your GET endpoint
      tags:
        - email
        - user
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/messages'
      operationId: getMessages
      description: Retrieve the messages for a user
    parameters:
      - type: string
        name: user_id
        in: path
        description: Used to resolve a user identity
        required: true
    post:
      summary: Create Message Request
      operationId: createMessageRequest
      description: Create a new message request
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              to:
                type: array
                items:
                  type: string
              cc:
                type: string
              bcc:
                type: string
              subject:
                type: string
              body:
                type: string
          description: New message request
      responses:
        '201':
          schema:
            type: string
            default: Created
          headers:
            Content-Location:
              type: string
              description: ''
          description: Created
      tags:
        - email
  '/{user_id}/messages/{message_id}':
    parameters:
      - type: string
        name: user_id
        in: path
        required: true
      - type: string
        name: message_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - email
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/message'
      operationId: getMessage
      description: Get a message for a user
definitions:
  std_links:
    description: Hypermedia links for a collection of persons
    type: object
    properties:
      emails__info:
        description: Hypermedia link for the default persons collection
        type: object
        required:
          - method
          - rel
          - href
        properties:
          method:
            default: GET
            enum:
              - GET
            type: string
          rel:
            default: self
            enum:
              - self
            type: string
          href:
            default: 'https://api.byu.edu/byuapi/persons/v3/'
            format: uri
            type: string
      emails__first:
        description: Hypermedia link for the persons collection at the first page
        type: object
        properties:
          method:
            default: GET
            enum:
              - GET
            type: string
          rel:
            default: persons__first
            enum:
              - persons__first
            type: string
          href:
            default: ':persons__first'
            format: uri
            type: string
        required:
          - method
          - rel
          - href
      emails__next:
        description: Hypermedia links format
        x-variable: persons__next
        type: object
        properties:
          method:
            enum:
              - GET
            type: string
          rel:
            type: string
          href:
            format: uri
            type: string
        required:
          - method
          - rel
          - href
      emails__last:
        description: Hypermedia links format
        type: object
        properties:
          method:
            default: GET
            enum:
              - GET
            type: string
          rel:
            default: persons__last
            type: string
          href:
            default: ':persons__last'
            format: uri
            type: string
        required:
          - method
          - rel
          - href
      emails__create:
        description: Hypermedia links format
        type: object
        properties:
          method:
            default: POST
            enum:
              - POST
            type: string
          rel:
            default: persons__create
            type: string
          href:
            default: 'https://api.byu.edu/byuapi/persons/v3/'
            format: uri
            type: string
        required:
          - method
          - rel
          - href
      emails__prev:
        description: Hypermedia links format
        x-variable: persons__prev
        type: object
        properties:
          method:
            enum:
              - GET
            type: string
          rel:
            type: string
          href:
            format: uri
            type: string
        required:
          - method
          - rel
          - href
    x-tags:
      - std
  std_validation_information:
    description: UAPI Validation Information
    type: array
    items:
      type: string
    additionalProperties: true
    x-tags:
      - std
  std_validation_response:
    description: UAPI Validation Response
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: number
      message:
        type: string
    additionalProperties: true
    x-tags:
      - std
  std_simple_metadata:
    description: UAPI Simple Metadata
    type: object
    additionalProperties: true
    x-tags:
      - std
    properties:
      validation_response:
        $ref: '#/definitions/std_validation_response'
      validation_information:
        $ref: '#/definitions/std_validation_information'
    required:
      - validation_response
  std_collection_metadata:
    description: UAPI Collection Metadata
    type: object
    additionalProperties: true
    x-tags:
      - std
    properties:
      collection_size:
        type: number
      validation_response:
        $ref: '#/definitions/std_validation_response'
      validation_information:
        $ref: '#/definitions/std_validation_information'
    required:
      - collection_size
      - validation_response
  message_id:
    description: The UUID of the email request
    type: object
    x-tags:
      - email
    properties:
      value:
        type: string
        format: uuid
        example: e4af5468-53d4-4389-acc6-e6fc371dce6e
      key:
        type: boolean
        default: true
      api_type:
        type: string
        default: system
    required:
      - value
      - key
      - api_type
  user_id:
    description: Identity for sending and recieving messages
    type: object
    properties:
      value:
        type: string
      api_type:
        type: string
        default: read-only
    required:
      - value
      - api_type
    x-tags:
      - user
  user_ids:
    description: Identity list for sending and recieving messages
    type: object
    x-tags:
      - user
    properties:
      value_array:
        type: array
        items:
          $ref: '#/definitions/user_id'
      api_type:
        type: string
        default: read-only
    required:
      - value_array
      - api_type
  message_subject:
    description: The subject of the message
    type: object
    x-tags:
      - email
    properties:
      value:
        type: string
      api_type:
        type: string
        default: read-only
    required:
      - value
      - api_type
  message_body:
    description: The body of the message
    type: object
    x-tags:
      - email
    properties:
      value:
        type: string
      api_type:
        type: string
        default: read-only
    required:
      - value
      - api_type
  message_status:
    description: A message request status
    type: object
    properties:
      value:
        type: string
        enum:
          - Pending
          - Sent
      api_type:
        type: string
        default: system
    required:
      - value
      - api_type
    x-tags:
      - email
  message_lifecycle_item:
    type: object
    x-tags:
      - email
    description: A lifecycle marker
    properties:
      status:
        $ref: '#/definitions/message_status'
      status_datetime:
        $ref: '#/definitions/std_datetime'
      status_by_id:
        $ref: '#/definitions/user_id'
    required:
      - status
      - status_datetime
      - status_by_id
  message_lifecycle:
    description: The lifecycle markers of the message request
    type: object
    x-tags:
      - email
    properties:
      object_array:
        type: array
        items:
          $ref: '#/definitions/message_lifecycle_item'
    required:
      - object_array
  std_datetime:
    description: The date-time that the request was created
    type: object
    minItems: 1
    maxItems: 2
    properties:
      value:
        type: string
      api_type:
        type: string
        format: date-time
    required:
      - value
      - api_type
    x-tags:
      - std
  message:
    title: message
    type: object
    description: Status information for an email request
    x-tags:
      - email
    properties:
      metadata:
        $ref: '#/definitions/std_simple_metadata'
      id:
        $ref: '#/definitions/message_id'
      to:
        $ref: '#/definitions/user_ids'
      cc:
        $ref: '#/definitions/user_ids'
      bcc:
        $ref: '#/definitions/user_ids'
      from:
        $ref: '#/definitions/user_id'
      subject:
        $ref: '#/definitions/message_subject'
      body:
        $ref: '#/definitions/message_body'
      lifecycle:
        $ref: '#/definitions/message_lifecycle'
    x-examples: {}
  messages:
    title: messages
    type: object
    x-tags:
      - email
    description: A collection of message requests
    properties:
      links:
        $ref: '#/definitions/std_links'
      metadata:
        $ref: '#/definitions/std_collection_metadata'
      values:
        type: array
        items:
          $ref: '#/definitions/message'
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
host: api.byu.edu
basePath: /byuapi/utility/email
securityDefinitions: {}
tags:
  - name: email
    description: Email Utility
  - name: std
    description: Shared Standard
  - name: user
    description: User Identity
