version: '3'
services:
  server:
    build:
      context: .
      args:
      - progress=plain
    ports:
    - "3000:3000"
    volumes:
    - ~/.aws:/home/node/.aws # Use AWS credentials from host
    environment:
      NODE_ENV: development
