version: 1

name: byuapi-email-utility

pipelines:
  stg: # prd-sim-appdev-oit-byu
    phases:
    - type: github
      name: Github
      owner: byu-oit
      repo: byuapi-email-utility
      branch: master
    - type: codebuild
      name: Build
      build_image: aws/codebuild/standard:3.0
    - type: handel
      name: DevDeploy
      environments_to_deploy:
      - dev
  prd: # prd-sim-appdev-oit-byu
    phases:
    - type: github
      name: Github
      owner: byu-oit
      repo: byuapi-email-utility
      branch: release
    - type: codebuild
      name: Build
      build_image: aws/codebuild/standard:3.0
    - type: handel
      name: Deploy
      environments_to_deploy:
      - prd
# https://handel-codepipeline.readthedocs.io
