version: 1
update_configs:
  - package_manager: "javascript"
    directory: "mailer"
    target_branch: master
    update_schedule: weekly
    default_reviewers:
      - stuft2
    ignore_updates:
      - match:
          update_type: "semver:major"
    automerged_updates:
      - match:
          update_type: "semver:patch"
  - package_manager: "javascript"
    directory: "server"
    target_branch: master
    update_schedule: weekly
    default_reviewers:
      - stuft2
    ignore_updates:
      - match:
          update_type: "semver:major"
    automerged_updates:
      - match:
          update_type: "semver:patch"
  - package_manager: "docker"
    directory: "/"
    target_branch: dev
    update_schedule: weekly
    default_reviewers:
      - stuft2
